name: Create release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        id: tag_release
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.tag_release.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
